

source 'https://github.com/BPModels/BPSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'BPNetwork_Example' do
  pod 'BPNetwork', :path => '../'

  target 'BPNetwork_Tests' do
    inherit! :search_paths

    
  end
end
